name:               "Ashish"
description:        "A blog about JavaScript, Design and Tools in genral"

url:                "http://thinker3197.github.io/blog"
author:             "thinker3197"
email:              "ashishgupta.3197@gmail.com"
gravatar_hash:      "de5c7e08016aeaa80d78eacbc33d60cc"
twitter:            "Ashishgupta3197"
github:             "thinker3197"
googleplus:         "+AshishGupta3197"
linkedin:           "ashish3197"
facebook:           "ashish.3197"

background:         "https://s-media-cache-ak0.pinimg.com/736x/cb/4c/e5/cb4ce5f8e6b99e65dede33a8ad531c07.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          :year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "Posts"
    href:           ""
  - name:           "About"
    href:           "about"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
