name:               "Ashish"
description:        "A blog about JavaScript, Design and Tools in genral"

url:                "http://thinker3197.github.io/blog"
author:             "thinker3197"
email:              "ashishgupta.3197@gmail.com"
gravatar_hash:      "de5c7e08016aeaa80d78eacbc33d60cc"
twitter:            "Ashishgupta3197"
github:             "thinker3197"
pinterest:          "jhondoe"
linkedin:           "ashish3197"
facebook:           "ashish.3197"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          :year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "Posts"
    href:           "blog"
  - name:           "About"
    href:           "about"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
